import { GoogleGenAI } from "@google/genai";
import { categorizeGeminiError } from "./errors";

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY || "" });

export async function generateGhostMannequin(
  file: File,
  customPrompt: string,
  category: string = 'Clothes',
  onStatusUpdate?: (status: string) => void
): Promise<string> {
  if (onStatusUpdate) onStatusUpdate('Processing image...');
  
  // Convert file to base64
  const base64Data = await new Promise<string>((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => {
      const result = reader.result as string;
      resolve(result.split(',')[1]); // Get only the base64 part
    };
    reader.onerror = reject;
    reader.readAsDataURL(file);
  });

  const mimeType = file.type;

  if (onStatusUpdate) onStatusUpdate('Removing background...');

  // Use the original image directly for background removal to preserve details
  const finalPrompt = `Remove the background from this image with surgical precision. 
  Keep the ${category.toLowerCase()} item EXACTLY as it is in the original image - do not simplify or alter its geometry. 
  Maintain the highest possible detail, including fine textures, sharp edges, and micro-details.
  Do NOT change any logos, ports, buttons, textures, or complex shapes. 
  The output must be professional grade, sharp, and clear.
  Isolate the item on a pure, solid white studio background (#FFFFFF). 
  ${customPrompt}`;

  try {
    const imageResponse = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            inlineData: {
              data: base64Data,
              mimeType: mimeType,
            },
          },
          {
            text: finalPrompt,
          },
        ],
      },
      config: {
        imageConfig: {
          aspectRatio: "1:1",
        },
      },
    });

    let generatedBase64 = "";
    for (const part of imageResponse.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        generatedBase64 = part.inlineData.data;
        break;
      }
    }

    if (!generatedBase64) {
      throw new Error("No image generated by Gemini. The prompt might have been blocked.");
    }

    return `data:image/png;base64,${generatedBase64}`;
  } catch (error) {
    throw categorizeGeminiError(error);
  }
}
